### ISSUE TITLE
Why do not show log when I set quiet to false?

### ISSUE THREAD

**Issue by zhaozhiming** [spenceralger/grunt-esvm#2]
HI,
I have set `options.quiet` to false, but grunt don't show the log. Did I missing something?  Thanks.

```
options: {
  branch: '2.0',
  quiet: false,
  fresh: true,
```

**Comment by spalger** [comment]
Hmm, that should do it. Are you sure that elasticsearch is logging something? Can you try setting the `--verbose` flag?

**Comment by zhaozhiming** [comment]
when I set verbose to true( add the `--verbose` follow the grunt command), it show the log now.  
It seems the `quiet` no effect to show log, the log show just dependent the `verbose` flag.   

The esvm.js file as follow:

``` js
module.exports = function (grunt) {
  var resolve = require('path').resolve;
  var directory = resolve(__dirname, '../../esvm');
  var dataDir = resolve(directory, 'data_dir');

  return {
    options: {
      branch: '2.0',
      fresh: false,
      quiet: false,
      config: {
        network: {
          host: '127.0.0.1'
        },
        http: {
          port: 9200
        },
        marvel: {
          agent: {
            enabled: false
          }
        }
      }
    },
    test: {
      options: {
        directory: resolve(directory, 'test'),
        purge: true
      }
    }
  };
};
```

**Comment by spalger** [comment]
@zhaozhiming I'm sorry, I forgot that we actually map the log levels from elasticsearch to grunt log levels [in the logClusterLogs](https://github.com/spalger/grunt-esvm/blob/9b667db62acd9421781894e95bd405d19c1fe7aa/lib/logClusterLogs.js#L13-L20) module. Are you trying to see the `DEBUG` messages? Because those are logged using grunt's debug logging, which is enabled with `--debug` or `--verbose`.

**Comment by zhaozhiming** [comment]
Ok, anyway, what I want is to see the esvm log. Now I can see log when I add `verbose` flag to grunt command. So thanks very much :+1:
